### ISSUE TITLE
Exception raised when loading `isort` 5 in venv that has `toml` installed

### ISSUE THREAD

**Issue by epage** [PyCQA/isort#1561]
```
Traceback (most recent call last):
  File "/Users/edpage/.cache/ddi/venv_fmt/bin/isort", line 5, in <module>
     from isort.main import main
  File "/Users/edpage/.cache/ddi/venv_fmt/lib/python3.8/site-packages/isort/__init__.py", line 2, in <module>
     from . import settings  # noqa: F401
   File "/Users/edpage/.cache/ddi/venv_fmt/lib/python3.8/site-packages/isort/settings.py", line 19, in <module>
     from ._vendored import toml
   File "/Users/edpage/.cache/ddi/venv_fmt/lib/python3.8/site-packages/isort/_vendored/toml/__init__.py", line 14, in <module>
     TomlPreserveCommentDecoder = decoder.TomlPreserveCommentDecoder
 AttributeError: module 'toml.decoder' has no attribute 'TomlPreserveCommentDecoder'
```

The vendored `toml` is doing a `from toml import decoder, encoder` which I think is pulling in the non-vendored `toml`.

I'll be working around this by splitting my venv between black and isort

**Comment by epage** [comment]
Oops., I selected the wrong version.  Doesn't happen with 5.6.4
