### ISSUE TITLE
AttributeError: type object 'File' has no attribute 'read'

### ISSUE THREAD

**Issue by wmowen** [PyCQA/isort#1607]
Traceback (most recent call last):
  File "/Users/momo/.pyenv/versions/3.6.0/envs/mbtpy/bin/isort", line 11, in <module>
    sys.exit(main())
  File "/Users/momo/.pyenv/versions/3.6.0/envs/mbtpy/lib/python3.6/site-packages/isort/main.py", line 953, in main
    for sort_attempt in attempt_iterator:
  File "/Users/momo/.pyenv/versions/3.6.0/envs/mbtpy/lib/python3.6/site-packages/isort/main.py", line 947, in <genexpr>
    for file_name in file_names
  File "/Users/momo/.pyenv/versions/3.6.0/envs/mbtpy/lib/python3.6/site-packages/isort/main.py", line 100, in sort_imports
    **kwargs,
  File "/Users/momo/.pyenv/versions/3.6.0/envs/mbtpy/lib/python3.6/site-packages/isort/api.py", line 303, in sort_file
    with io.File.read(filename) as source_file:
AttributeError: type object 'File' has no attribute 'read'

**Comment by anirudnits** [comment]
@wmowen can you provide any other details on this issue? like the how you executed isort, config file etc.

**Comment by timothycrosley** [comment]
This is a duplicate of: https://github.com/PyCQA/isort/issues/1593 which is fixed in isort development branch and awaiting release by end of month. More details are on the linked ticket, but the TLDR is that it's caused by a bug in Python 3.6.0 - which has been fixed in Python itself within the 3.6 series so isn't caught by isort's CI/CD which can't reasonably test against all minor releases of Python
