### ISSUE TITLE
skip_gitignore requires git installed, but this is not documented

### ISSUE THREAD

**Issue by uhbif19** [PyCQA/isort#1746]
Using `isort` in my CI pipeline, I encountered some error which I did not get on local computer. It turned out CI environment lacked `git`, which is used by `skip_gitignore` command.

Code just exec `git`, so absence of git leads to runtime error:

```
Traceback (most recent call last):
  File "/usr/bin/isort", line 33, in <module>
    sys.exit(load_entry_point('isort==5.8.0', 'console_scripts', 'isort')())
  File "/usr/lib/python3.9/site-packages/isort/main.py", line 1159, in main
    for sort_attempt in attempt_iterator:
  File "/usr/lib/python3.9/site-packages/isort/main.py", line 1143, in <genexpr>
    attempt_iterator = (
  File "/usr/lib/python3.9/site-packages/isort/files.py", line 37, in find
    if config.is_skipped(Path(filepath)):
  File "/usr/lib/python3.9/site-packages/isort/settings.py", line 523, in is_skipped
    result = subprocess.run(  # nosec # skipcq: PYL-W1510
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git'
```

I think documenting it in `skip_gitignore` or returning error message suggesting installing of git would make behavior more clear.

**Comment by timothycrosley** [comment]
This is a good call out! I've updated the docs to mention the requirement (in the CLI and website)
