### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 1340: illegal multibyte sequence

### ISSUE THREAD

**Issue by YeKelvin** [PyCQA/isort#1767]
python 3.8
isort 5.9.1.
windows 10.
use in vscode.

> e:\personal-project\xxx/.cache/virtualenvs/xxx-py3.8/Scripts/isort - --diff
cwd: e:\personal-project\qa-cloud\qa-cloud-backend\app\common\decorators
Error 2021-06-28 15:11:04: Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main

Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main

Error 2021-06-28 15:11:04: Failed to format imports for 'e:\personal-project\xxx\app\common\decorators\service.py'. Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main

Error 2021-06-28 15:11:04:     return _run_code(code, main_globals, None,
  File "C:\Program Files\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "e:\personal-project\xxx\.cache\virtualenvs\xxx-py3.8\Scripts\isort.exe\__main__.py", line 7, in <module>
  File "e:\personal-project\xxx\.cache\virtualenvs\xxx-py3.8\lib\site-packages\isort\main.py", line 1101, in main
    api.sort_stream(
  File "e:\personal-project\xxx\.cache\virtualenvs\xxx-py3.8\lib\site-packages\isort\api.py", line 164, in sort_stream
    changed = sort_stream(
  File "e:\personal-project\xxx\.cache\virtualenvs\xxx-py3.8\lib\site-packages\isort\api.py", line 209, in sort_stream
    changed = core.process(
  File "e:\personal-project\xxx\.cache\virtualenvs\xxx-py3.8\lib\site-packages\isort\core.py", line 379, in process
    parsed_content = parse.file_contents(import_section, config=config)
  File "e:\personal-project\xxx\.cache\virtualenvs\xxx-py3.8\lib\site-packages\isort\parse.py", line 437, in file_contents
    placed_module = finder(import_from)
  File "e:\personal-project\xxx\.cache\virtualenvs\xxx-py3.8\lib\site-packages\isort\place.py", line 17, in module

Error 2021-06-28 15:11:04:     return module_with_reason(name, config)[0]
  File "e:\personal-project\xxx\.cache\virtualenvs\xxx-py3.8\lib\site-packages\isort\place.py", line 27, in module_with_reason
    or _src_path(name, config)
  File "e:\personal-project\xxx\.cache\virtualenvs\xxx-py3.8\lib\site-packages\isort\place.py", line 84, in _src_path

Error 2021-06-28 15:11:04:     and _is_namespace_package(module_path, config.supported_extensions)
  File "e:\personal-project\xxx\.cache\virtualenvs\xxx-py3.8\lib\site-packages\isort\place.py", line 129, in _is_namespace_package
    file_start = open_init_file.read(4096)
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 1340: illegal multibyte sequence

**Comment by StarHeartHunt** [comment]
I'm also facing this issue.

Any update on this?

**Comment by yitianlian** [comment]
I also facing it
