### ISSUE TITLE
isort over Language Server Protocol and VS Code extension

### ISSUE THREAD

**Issue by karthiknadig** [PyCQA/isort#1904]
The [Python team for VS Code](https://github.com/microsoft/vscode-python) has been working on putting various tools we support behind [LSP](https://microsoft.github.io/language-server-protocol/) and breaking them out into their own extensions This work is now far enough along that we wanted to share the extension prototypes for your tool with you and see if you had any interest in owning the extension or the Python-based LSP server backing it yourself?

If you don't want to take on that responsibility that's totally fine and understandable! If you want to leave the extension to us, then we would publish the extension on the [VS Code Marketplace](https://marketplace.visualstudio.com/VSCode) ourselves. We also plan to publish the extension as open source and support the extension for as long as we felt it made sense based on usage numbers. But due to the difficulty of migrating extension ownership, we wanted to ask early whether you wanted to own the extension from the start? If you did want to own the extension we would give you the code, help you publish to the VS Code Marketplace, and do anything else we can to help you be successful with this.

We have attached a zip file to this issue containing a prototype extension to give you an idea of what we are planning. You can download it, extract the `.vsix` file, and then [install the VSIX](https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix) to try it out [python-isort.zip](https://github.com/PyCQA/isort/files/8112249/python-isort.zip). This prototype version was built with python 3.10 and bundles isort v5.10.1 (as fallback if nothing is found in your environment).

To be very clear, there's no pressure or expectations from us. We just want to make sure you as a project had an opportunity to own this extension instead of us from the get-go before the extension gained traction.

**Comment by karthiknadig** [comment]
As an example, if you have code like this:
```python
import unittest
import re
class TestSum2(unittest.TestCase):
    def test_sum2(self):
        self.assertEqual(sum([1, 2, 3]), 6, "Should be 6")

    def test_sum2_tuple(self):
        self.assertEqual(sum((1, 2, 2)), 6, "Should be 6")


if __name__ == "__main__":
    unittest.main()
```
You would see diagnostics like this:
![image](https://user-images.githubusercontent.com/3840081/155030592-780aa179-0f4e-4634-9a3e-489a251aad98.png)

You can trigger import sorting using `shift+alt+o`:
![image](https://user-images.githubusercontent.com/3840081/155030700-0d98b0c2-046f-407c-901c-ca79c3bf31e2.png)
The first one there is from the prototype extension, the second one comes from python extension. Click on the first one.

It should get formatted like this:
![image](https://user-images.githubusercontent.com/3840081/155030814-ea3f14b1-6b50-49ce-919c-b218b0b41396.png)

You can add this to your settings to automatically do this for you and work with `black`. I have used black extension prototype in the settings below. you can get that here https://github.com/psf/black/issues/2883:
```
    "[python]": {
        "editor.defaultFormatter": "kanadig.python-black"
    },
    "editor.codeActionsOnSave": { "source.organizeImports": true },
    "editor.formatOnSave": true,
    "python.isortArgs": ["--profile", "black"]
```

**Comment by markusdd** [comment]
as mentioned in #18664 I strongly vote for this extension to be published, works like a charm and is easier to handle than the current built-in sorting solution

**Comment by markusdd** [comment]
Locally this extension works great, but I now observed an issue when it is used in conjunction with the Remote SSH extension.
I have installed it locally and also on the remote, but I get the following error and it cannot start up the isort server:

```
[ERROR 2022-3-21 19:23:50.253]: Error initializing python:  [TypeError: n.environment.onDidActiveInterpreterChanged is not a function
	at c (/home/mkrause/.vscode-server/extensions/kanadig.python-isort-0.0.1/dist/extension.js:1:72910)
	at t.getInterpreterPath (/home/mkrause/.vscode-server/extensions/kanadig.python-isort-0.0.1/dist/extension.js:1:73191)
	at /home/mkrause/.vscode-server/extensions/kanadig.python-isort-0.0.1/dist/extension.js:1:301113
	at m._executeContributedCommand (/home/mkrause/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:85:30760)
	at m.$executeContributedCommand (/home/mkrause/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:85:31302)
	at i._doInvokeHandler (/home/mkrause/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:89:13826)
	at i._invokeHandler (/home/mkrause/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:89:13510)
	at i._receiveRequest (/home/mkrause/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:89:12171)
	at i._receiveOneMessage (/home/mkrause/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:89:10841)
	at /home/mkrause/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:89:8947
	at u.invoke (/home/mkrause/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at v.fire (/home/mkrause/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
	at d.fire (/home/mkrause/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:66:19034)
	at /home/mkrause/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:104:34275
	at u.invoke (/home/mkrause/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at v.fire (/home/mkrause/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
	at d.fire (/home/mkrause/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:66:19034)
	at o._receiveMessage (/home/mkrause/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:66:23615)
	at /home/mkrause/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:66:21149
	at u.invoke (/home/mkrause/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at v.fire (/home/mkrause/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
	at v.acceptChunk (/home/mkrause/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:66:15865)
	at /home/mkrause/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:66:14995
	at u.invoke (/home/mkrause/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at v.fire (/home/mkrause/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
	at l._processReadQueue (/home/mkrause/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/vs/workbench/api/node/extensionHostProcess.js:104:21279)]
[Error - 7:23:50 PM] Starting client failed
Error: Unsupported server configuration {
    "command": "",
    "args": [
        "/home/mkrause/.vscode-server/extensions/kanadig.python-isort-0.0.1/bundled/formatter/format_server.py"
    ]
}
	at /home/mkrause/.vscode-server/extensions/kanadig.python-isort-0.0.1/dist/extension.js:1:244000

```

any advice?

**Comment by karthiknadig** [comment]
It is failing because the core extension API name changed `onDidActiveInterpreterChanged` to `onDidActiveEnvironmentChanged`. 

We now have a proper repro and will soon publish a pre-release version: https://github.com/microsoft/vscode-isort

**Comment by markusdd** [comment]
thanks for the super quick response!

is there a .vsix I can use in the mean time or how can I use this in the meantime until there is a release?

**Comment by karthiknadig** [comment]
Try this one: https://github.com/microsoft/vscode-isort/suites/6198532929/artifacts/218534859

**Comment by markusdd** [comment]
works like a charm! Thanks a lot, really looking forward to the release.

By the way, is there already a change-ticket for the python extension removing i-sorting from there? because each time on saving it still produces this error message in conjunction with .venvs that we talked about in another ticket.

**Comment by karthiknadig** [comment]
If you use the pre-release version of the python extension it detects if there isort extension and disables its own import sorting.
