### ISSUE TITLE
git_ignore documentation could be improved

### ISSUE THREAD

**Issue by Foryah** [PyCQA/isort#1920]
I was checking [here](https://pycqa.github.io/isort/docs/configuration/options) if there's a way for isort to ignore the files from my `.gitignore` without requiring `git` installed (using it in a Jenkins pipeline with the `--check` flag). I stumbled upon `git_ignore` which looked promising and I had two issues with it: 

1. It didn't mention that it's only working when `skip_gitignore` is `True` which seems to be the case when you check the code
2. It mentions that it should be set to `True` but the actual value it expects is a `dict` so it's very confusing how you should be using it

I think the documentation can be improved to make the previous two points clearer.

And a little bit of an offtopic: You think a feature to ignore the contents of `.gitignore` using basic regex instead of relying of `git` to be present is a good idea? I know for CI that would be great cause you usually use slim images that don't have a lot of system dependencies installed. Should we create an issue for this as well?

**Comment by sparrowt** [comment]
I also stumbled upon https://pycqa.github.io/isort/docs/configuration/options.html#git-ignore and was confused why it says `True` but also `Dict`.

I tried using it:
```toml
[tool.isort]
git_ignore = true
```
and isort explodes like this:
```
$ isort . --check

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "PATH\to\isort.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "PATH\to\Lib\site-packages\isort\main.py", line 1125, in main
    config = Config(**config_dict)
  File "PATH\to\Lib\site-packages\isort\settings.py", line 514, in __init__
    raise UnsupportedSettings(unsupported_config_errors)
isort.exceptions.UnsupportedSettings: isort was provided settings that it doesn't support:

        - git_ignore = True  (source: 'PATH\to\pyproject.toml')

For a complete and up-to-date listing of supported settings see: https://pycqa.github.io/isort/docs/configuration/options.
```
so actually it seems to be completely defunct AFAICS

**Comment by sparrowt** [comment]
Yeah, https://github.com/PyCQA/isort/commit/e16806990ed862ac2bdc3125060d1a35741c1e83 removed `git_ignore` from the `_Config` class, but didn't remove it from the documentation. I'll open a PR to clean this up.

**Comment by sparrowt** [comment]
Removed outdated docs in https://github.com/PyCQA/isort/pull/2531
