### ISSUE TITLE
`--config-root` flag doesn't work

### ISSUE THREAD

**Issue by emosenkis** [PyCQA/isort#1990]
```
$ isort --check --config-root .. .
Traceback (most recent call last):
  File "/home/eitan/.pyenv/versions/venv/bin/isort", line 8, in <module>
    sys.exit(main())
  File "/home/eitan/.pyenv/versions/3.9.7/envs/venv/lib/python3.9/site-packages/isort/main.py", line 1108, in main
    config = Config(**config_dict)
  File "/home/eitan/.pyenv/versions/3.9.7/envs/venv/lib/python3.9/site-packages/isort/settings.py", line 524, in __init__
    raise UnsupportedSettings(unsupported_config_errors)
isort.exceptions.UnsupportedSettings: isort was provided settings that it doesn't support:

        - config_root = ..  (source: 'runtime')

For a complete and up-to-date listing of supported settings see: https://pycqa.github.io/isort/docs/configuration/options.

**Comment by kaste** [comment]
Yeah, only implemented when you also set `--resolve-all-configs`.  So the error is not helping here
