### ISSUE TITLE
Doesn't support python 3.12

### ISSUE THREAD

**Issue by Harry-Jing** [PyCQA/isort#2198]
```cli
Traceback (most recent call last):
  File "/Users/harry/.cache/pre-commit/repog8bytrt8/py_env-python3.12/bin/isort", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/harry/.cache/pre-commit/repog8bytrt8/py_env-python3.12/lib/python3.12/site-packages/isort/main.py", line 1121, in main
    config = Config(**config_dict)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/harry/.cache/pre-commit/repog8bytrt8/py_env-python3.12/lib/python3.12/site-packages/isort/settings.py", line 528, in __init__
    super().__init__(sources=tuple(sources), **combined_config)
  File "<string>", line 105, in __init__
  File "/Users/harry/.cache/pre-commit/repog8bytrt8/py_env-python3.12/lib/python3.12/site-packages/isort/settings.py", line 261, in __post_init__
    raise ValueError(
ValueError: The python version 312 is not supported. You can set a python version with the -py or --python-version flag. The following versions are supported: ('all', '2', '27', '3', '310', '311', '36', '37', '38', '39')
```

**Comment by staticdev** [comment]
@Harry-Jing now it does.
