### ISSUE TITLE
--sort-reexports results in isort not being able to parse file

### ISSUE THREAD

**Issue by mzmm1000** [PyCQA/isort#2286]
**Python version 3.12**
**isort version: 5.13.2**

Test file `test.py`:
```
#!/usr/bin/env python
import importlib.metadata

__all__ = [
    "FooType",
    "BarType",
    "some_method",
]
__version__ = importlib.metadata.version("my-package")
```

Calling `isort --srx test.py` results in:

`isort/main.py:105: UserWarning: Unable to parse file test.py due to too many values to unpack (expected 2)`

The exception is actually triggered [here](https://github.com/PyCQA/isort/blob/c655831799765e9593989ee12faba13b6ca391a5/isort/literal.py#L50) - somehow, both assignments to `__all__` and `__version__` end up in `code`.

It works if an empty line between both assignments is introduced (or any other code, for that matter).

**Comment by DanielNoord** [comment]
Traceback is as follows:
```
Traceback (most recent call last):
  File "/home/daniel-vannoord/Documents/github/isort/.venv/bin/isort", line 10, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/daniel-vannoord/Documents/github/isort/isort/main.py", line 1236, in main
    for sort_attempt in attempt_iterator:
                        ^^^^^^^^^^^^^^^^
  File "/home/daniel-vannoord/Documents/github/isort/isort/main.py", line 1220, in <genexpr>
    sort_imports(  # type: ignore
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
        file_name,
        ^^^^^^^^^^
    ...<6 lines>...
        config_trie=config_trie,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/daniel-vannoord/Documents/github/isort/isort/main.py", line 96, in sort_imports
    incorrectly_sorted = not api.sort_file(
                             ~~~~~~~~~~~~~^
        file_name,
        ^^^^^^^^^^
    ...<3 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/home/daniel-vannoord/Documents/github/isort/isort/api.py", line 435, in sort_file
    changed = sort_stream(
        input_stream=source_file.stream,
    ...<4 lines>...
        extension=extension,
    )
  File "/home/daniel-vannoord/Documents/github/isort/isort/api.py", line 212, in sort_stream
    changed = core.process(
        input_stream,
    ...<3 lines>...
        raise_on_skip=raise_on_skip,
    )
  File "/home/daniel-vannoord/Documents/github/isort/isort/core.py", line 142, in process
    isort.literal.assignment(
    ~~~~~~~~~~~~~~~~~~~~~~~~^
        code_sorting_section,
        ^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        config=_indented_config(config, indent),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
  File "/home/daniel-vannoord/Documents/github/isort/isort/literal.py", line 51, in assignment
    variable_name, literal = code.split("=")
    ^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2, got 3)
```
