### ISSUE TITLE
Python 3.13 support

### ISSUE THREAD

**Issue by mayty** [PyCQA/isort#2305]
Python 3.13 was [released](https://www.python.org/downloads/release/python-3130/) on Oct. 7, 2024 and is not supported as `py_version` as of now:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\WinFolders\Documents\PyCharmProjects\asemu\.venv\Scripts\isort.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "D:\WinFolders\Documents\PyCharmProjects\asemu\.venv\Lib\site-packages\isort\main.py", line 1123, in main
    config = Config(**config_dict)
  File "D:\WinFolders\Documents\PyCharmProjects\asemu\.venv\Lib\site-packages\isort\settings.py", line 531, in __init__
    super().__init__(sources=tuple(sources), **combined_config)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 105, in __init__
  File "D:\WinFolders\Documents\PyCharmProjects\asemu\.venv\Lib\site-packages\isort\settings.py", line 264, in __post_init__
    raise ValueError(
    ...<3 lines>...
    )
ValueError: The python version 313 is not supported. You can set a python version with the -py or --python-version flag. The following versions are supported: ('all', '2', '27', '3', '310', '311', '312', '36', '37', '38', '39')
```

**Comment by DanielNoord** [comment]
Fixed with https://github.com/PyCQA/isort/pull/2306
