### ISSUE TITLE
Cannot handle non-ASCII characters

### ISSUE THREAD

**Issue by kseistrup** [PyCQA/isort#28]
Here's two more or less identical python scripts, one of which contains UTF-8 encoded characters:

``` sh
$ cat test1.py
# -*- coding: utf-8 -*-
"""abc"""
$ cat test2.py
# -*- coding: utf-8 -*-
"""æøå"""
$ python test1.py && echo ok
ok
$ python test2.py && echo ok
ok
$ isort test1.py && echo ok
ok
$ isort test2.py && echo ok
Traceback (most recent call last):
  File "/usr/local/bin/isort", line 43, in <module>
    SortImports(file_name, **arguments)
  File "/usr/local/lib/python2.7/dist-packages/isort/isort.py", line 73, in __init__
    self.in_lines = file_contents.split("\n")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 27: ordinal not in range(128)
$ 
```

Boom!

**Comment by jmfederico** [comment]
Hi!

Sorry to re-open such an old thread.

I just ran  into this problem when running isort on OSX yosemite, with python 3.4.2 and isort 3.9.4

The problems seems to be that OSX doesn't have LANG set to anything by default, so when isort opens the file to check (line 94), it doesn't specify an encoding, which then default to "ASCII" on OSX.

If LANG is set to something like en_US.UTF-8 the problem goes away, but will break in systems where for any reason changing the locale is not an option.

The second link I put here talks about a “Unicode sandwich” approach. That might solve the problem.

http://robjwells.com/post/61198832297/get-your-us-ascii-out-of-my-face
http://nedbatchelder.com/text/unipain.html

```shell
Traceback (most recent call last):
  File "/Users/fjm/Development/acora_dj/venv/bin/isort", line 11, in <module>
    sys.exit(main())
  File "/Users/fjm/Development/acora_dj/venv/lib/python3.4/site-packages/isort/main.py", line 119, in main
    incorrectly_sorted = SortImports(file_name, **arguments).incorrectly_sorted
  File "/Users/fjm/Development/acora_dj/venv/lib/python3.4/site-packages/isort/isort.py", line 95, in __init__
    file_contents = file_to_import_sort.read()
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2709: ordinal not in range(128)
```
